# Reference: https://dev.to/pierresaid/deploy-node-projects-to-github-pages-with-github-actions-4jco
name: Build Test
on:
  push:
    branches:
      - develop
      - feature/*
      - release/*
      - hotfix/*
      - dependabot/*
jobs:
  build-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x, 18.x]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1
        with:
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install, then begin Testing ☢️
        run: |
          npm install -g pnpm
          pnpm install --no-frozen-lockfile
          pnpm run lint
      - name: Build 🔧
        run: |
          pnpm run build
